"""empty message

Revision ID: 458fd35d4fd1
Revises: 
Create Date: 2017-08-22 11:08:49.433917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458fd35d4fd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('url_video', sa.String(length=200), nullable=True),
    sa.Column('url_img', sa.String(length=200), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    op.drop_table('seasons')
    # ### end Alembic commands ###
