"""empty message

Revision ID: bff80012af29
Revises: bc551d51f28c
Create Date: 2017-08-23 01:03:44.477637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bff80012af29'
down_revision = 'bc551d51f28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episodes', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False, server_default=sa.func.current_timestamp())
    op.alter_column('seasons', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,  server_default=sa.func.current_timestamp())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('seasons', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    op.alter_column('episodes', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
